# Generated by Django 3.0.7 on 2020-09-07 12:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTypes',
            fields=[
                ('mediaTypeID', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=50)),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('projectUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('mediaID', models.AutoField(primary_key=True, serialize=False)),
                ('mediaName', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('uploadDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('mediaType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.MediaTypes')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Projects')),
            ],
        ),
    ]
