# Generated by Django 3.0.7 on 2020-09-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='mediaUrl',
            field=models.URLField(default='haha'),
            preserve_default=False,
        ),
    ]
