# Generated by Django 3.0.7 on 2020-09-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_media_mediaurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projectUrl',
            new_name='projectThumbnail',
        ),
    ]
