# Generated by Django 3.0.7 on 2020-09-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200909_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectDescription',
            field=models.TextField(default='Lorem ipsum is just a dummy text used in typography when you are not sure what will be written or you just dont feel like typing stuff... but I literally typed this', max_length=1000),
            preserve_default=False,
        ),
    ]
