# Generated by Django 3.0.7 on 2020-09-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_projects_projectdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='mediaName',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
